.\" Manpage for calc.
.\" Contact ceo@mast3rsoft.com to correct errors or typos.
.TH man 1 "Sat 2 Nov 2019" "1.0" "calc man page"
.SH NAME
calc \- perform calculation in infix notation 
.SH SYNOPSIS
calc [arg1] [operator] [arg2]
.SH DESCRIPTION
calc is a calculator, arg1 and arg2 must be an Int or a float or a Double. The operator  must be + - / *
.SH OPTIONS
.B -sqrt Uses square root, you  can use pipe with it. It acepts only one argument.
-p  You can pipe with this
.SH SEE ALSO
bc
.SH BUGS
Be carful if you use * because in bash * means all files, so please escape it. Or if you want, you can use x for multipliying
.SH AUTHOR
Jakob Nikolaus Neufeld (jakob.n.neufeld@gmail.com)
.SH NOTES
I will be ading new operators. If you have a new operator that you want to add please contact me.
Also, POWERERD WITH SWIFT
